# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.IntegerField(default=0)),
                ('move_in', models.DateField()),
                ('deposit', models.IntegerField(default=0)),
                ('amenity', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=500)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gender_pref', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('race_pref', models.IntegerField(choices=[(1, 'Malay'), (2, 'Chinese'), (3, 'Indian'), (4, 'Others')])),
                ('photo', models.ImageField(upload_to='advertisement/photo/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('sent_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('race', models.IntegerField(choices=[(1, 'Malay'), (2, 'Chinese'), (3, 'Indian'), (4, 'Others')])),
                ('phone', models.CharField(max_length=10)),
                ('lifestyle_info', models.CharField(max_length=500)),
                ('gender_pref', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('race_pref', models.IntegerField(choices=[(1, 'Malay'), (2, 'Chinese'), (3, 'Indian'), (4, 'Others')])),
                ('budget_pref', models.IntegerField(default=0)),
                ('move_in_pref', models.DateField()),
                ('avatar', models.ImageField(upload_to='user/avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rated_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rater', to=settings.AUTH_USER_MODEL)),
                ('rated_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
