# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0004_auto_20161210_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget_pref',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender_pref',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lifestyle_info',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='move_in_pref',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race_pref',
            field=models.IntegerField(blank=True, choices=[(1, 'Malay'), (2, 'Chinese'), (3, 'Indian'), (4, 'Others')]),
        ),
    ]
