# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0005_auto_20161210_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(max_length=500),
        ),
    ]
