# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0011_auto_20161210_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='amenity',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='race_pref',
            field=models.IntegerField(choices=[(2, 'Chinese'), (1, 'Malay'), (3, 'Indian'), (4, 'Others')]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rule',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.IntegerField(blank=True, choices=[(2, 'Chinese'), (1, 'Malay'), (3, 'Indian'), (4, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race_pref',
            field=models.IntegerField(blank=True, choices=[(2, 'Chinese'), (1, 'Malay'), (3, 'Indian'), (4, 'Others')], null=True),
        ),
    ]
