# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0012_auto_20161210_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='race_pref',
            field=models.IntegerField(choices=[(1, 'Chinese'), (2, 'Malay'), (3, 'Indian'), (4, 'Others')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.IntegerField(blank=True, choices=[(1, 'Chinese'), (2, 'Malay'), (3, 'Indian'), (4, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race_pref',
            field=models.IntegerField(blank=True, choices=[(1, 'Chinese'), (2, 'Malay'), (3, 'Indian'), (4, 'Others')], null=True),
        ),
    ]
