# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0015_auto_20161212_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(upload_to='advertisement/'),
        ),
    ]
