# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0016_auto_20161212_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
