# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0017_auto_20161227_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_pref',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.IntegerField(choices=[(1, 'Chinese'), (2, 'Malay'), (3, 'Indian'), (4, 'Others')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race_pref',
            field=models.IntegerField(choices=[(1, 'Chinese'), (2, 'Malay'), (3, 'Indian'), (4, 'Others')], default=0),
        ),
    ]
