# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-01 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0018_auto_20170101_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_pref',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.IntegerField(blank=True, choices=[(1, 'Chinese'), (2, 'Malay'), (3, 'Indian'), (4, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race_pref',
            field=models.IntegerField(blank=True, choices=[(1, 'Chinese'), (2, 'Malay'), (3, 'Indian'), (4, 'Others')], null=True),
        ),
    ]
