# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0019_auto_20170101_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='race_pref',
            field=models.IntegerField(choices=[(2, 'Malay'), (1, 'Chinese'), (3, 'Indian'), (4, 'Others')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.IntegerField(blank=True, choices=[(2, 'Malay'), (1, 'Chinese'), (3, 'Indian'), (4, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race_pref',
            field=models.IntegerField(blank=True, choices=[(2, 'Malay'), (1, 'Chinese'), (3, 'Indian'), (4, 'Others')], null=True),
        ),
    ]
