# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0020_auto_20170102_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='place_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='gender_pref',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='race_pref',
            field=models.IntegerField(choices=[(0, 'Malay'), (1, 'Chinese'), (2, 'Indian'), (3, 'Others')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender_pref',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.IntegerField(blank=True, choices=[(0, 'Malay'), (1, 'Chinese'), (2, 'Indian'), (3, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race_pref',
            field=models.IntegerField(blank=True, choices=[(0, 'Malay'), (1, 'Chinese'), (2, 'Indian'), (3, 'Others')], null=True),
        ),
    ]
