# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0022_profile_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device_token',
        ),
    ]
