# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroomieapp', '0023_remove_profile_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
